language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
    - add-on
    - extra

before_install:
  - openssl aes-256-cbc -K $encrypted_e5b50b8dd3ec_key -iv $encrypted_e5b50b8dd3ec_iv -in keystore.tar.enc -out keystore.tar -d
  - tar -xvf keystore.tar

script:
  - ./gradlew assembleRelease
  - ls -lh app/build/outputs/apk/release/app-release.apk